# Generated by Django 3.2.6 on 2021-09-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='client',
            new_name='reciver',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='owner',
            new_name='sender',
        ),
    ]
