# Generated by Django 3.2.6 on 2021-09-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210911_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='keywords',
            new_name='specs',
        ),
    ]
