# Generated by Django 3.2.6 on 2021-09-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_keywords_product_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
    ]
