# Generated by Django 3.2.6 on 2021-09-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
