# Generated by Django 3.2.6 on 2021-09-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='msg',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/chat-images/'),
        ),
    ]
