# Generated by Django 3.2.6 on 2021-09-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='products',
        ),
        migrations.AddField(
            model_name='saved',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_saved', to='products.product'),
        ),
    ]
