# Generated by Django 3.2.6 on 2021-09-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210928_0041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
